# Base image
FROM mcr.microsoft.com/dotnet/aspnet:9.0.8 AS base
WORKDIR /app
EXPOSE 5000

# Build stage
FROM mcr.microsoft.com/dotnet/sdk:9.0.8 AS build
WORKDIR /src
COPY ["Portfolio.Web.csproj", "./"]
RUN dotnet restore "./Portfolio.Web.csproj"
COPY . .
RUN dotnet publish "./Portfolio.Web.csproj" -c Release -o /app/publish

# Final stage
FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Portfolio.Web.dll"]
